# TCP port on which Beetle is listening for connections
port 5555
# Directory where database files are stored
storage_directory ./example/db
# Number of database instances to run. For parallelization, the provided value
# should be equal to the number of CPU cores.
database_shards 1
# Interval, in seconds, for compaction operation. If we don't want to allow
# merge interval, use value `SKIP`. Allowed identiifiers are
# hours (h), minutes (m), seconds (s) (case insensitive).
merge_interval 60s
# Interval, in seconds, for log rotation. If we don't want to allow log
# rotation, use value `SKIP`.  Allowed identiifiers are hours (h), minutes (m),
# seconds (s) (case insensitive).
log_rotation_interval 60s
# Maximum allowed log file size. Allowed identifiers are kb, mb, gb (case
# insensitive). Log rotation is triggered once we breach this allowed file
# size.
log_file_size 1mb
